// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as CountrySelect$RescriptPractice from "./CountrySelect.bs.js";

import './index.css'
;

function App(Props) {
  var match = React.useState(function () {
        
      });
  var setSelectedCountryValue = match[1];
  var match$1 = React.useState(function () {
        return false;
      });
  var setIsError = match$1[1];
  var onChange = function (newSelectedCountryValue) {
    return Curry._1(setSelectedCountryValue, (function (param) {
                  return newSelectedCountryValue;
                }));
  };
  var tmp;
  if (match$1[0]) {
    tmp = React.createElement("div", {
          className: "errorMessage"
        }, "Error: failed fetching or parsing countries data");
  } else {
    var tmp$1 = {
      onChange: onChange,
      onError: (function (param) {
          return Curry._1(setIsError, (function (param) {
                        return true;
                      }));
        })
    };
    var tmp$2 = match[0];
    if (tmp$2 !== undefined) {
      tmp$1.selectedCountryValue = Caml_option.valFromOption(tmp$2);
    }
    tmp = React.createElement(CountrySelect$RescriptPractice.make, tmp$1);
  }
  return React.createElement("div", {
              className: "app"
            }, React.createElement("h3", undefined, "CountrySelect Demo"), tmp);
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
