// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Caml_array from "bs-platform/lib/es6/caml_array.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as ReactWindow from "react-window";

function ReactSelectMenu(Props) {
  var menuProps = Props.menuProps;
  var listRef = Props.listRef;
  var getSelectedIndex = Props.getSelectedIndex;
  var selectedValues = Curry._1(menuProps.getValue, undefined);
  var initialIndex = Belt_Option.mapWithDefault(selectedValues, 0, getSelectedIndex);
  var initialScrollOffset = Math.imul(initialIndex, 35);
  var itemCount = React.Children.count(menuProps.children);
  var childrenArray = React.Children.toArray(menuProps.children);
  return React.createElement(ReactWindow.FixedSizeList, {
              height: menuProps.maxHeight,
              itemCount: itemCount,
              itemSize: 35,
              initialScrollOffset: initialScrollOffset,
              ref: listRef,
              children: (function (props) {
                  return React.createElement("div", {
                              style: props.style
                            }, Caml_array.get(childrenArray, props.index));
                })
            });
}

var height = 35;

var make = ReactSelectMenu;

export {
  height ,
  make ,
  
}
/* react Not a pure module */
